version: '3'
services:
  node:
    image: "node:latest"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api:/home/node/app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    command: "npm run start:prod"